name: waestro_mobile
description: "A weather app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/moon_phases/new_moon.svg
    - lib/assets/images/moon_phases/waxing_crescent.svg
    - lib/assets/images/moon_phases/first_quarter.svg
    - lib/assets/images/moon_phases/waxing_gibbous.svg
    - lib/assets/images/moon_phases/full_moon.svg
    - lib/assets/images/moon_phases/waning_gibbous.svg
    - lib/assets/images/moon_phases/third_quarter.svg
    - lib/assets/images/moon_phases/waning_crescent.svg